Dev/ykovalova/update path with sts
dotnet/install-scripts pull request #330
Opened 2022-11-09 09:07 UTC by YuliiaKovalova

2022-11-09 17:13 UTC, jamshedd requested changes

2022-11-09 17:13 UTC, jamshedd commented on src/dotnet-install.ps1
> +    - STS - Standard Term Support
```suggestion
    - STS - the most recent Standard Term Support release
```

2022-11-09 17:13 UTC, jamshedd commented on src/dotnet-install.sh
> +            echo "          - STS - Standard Term Support"
```suggestion
            echo "          - STS - the most recent Standard Term Support release"
```

2022-11-09 17:19 UTC, jamshedd approved these changes

2022-11-10 09:06 UTC, donJoseLuis approved these changes

2022-11-10 09:10 UTC, merged